language: r
latex: false
fortran: false
pandoc: false

warnings_are_errors: true
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - libapparmor-dev
  
r_github_packages:
  - antonellilab/outsider
  
script:
  - Rscript -e 'outsider::module_test(repo = "dombennett/om..pyrate")'
